name: docker
on:
  push:
    paths:
      - 'aicovergen/**/*'
      - '.github/workflows/docker.yml'
jobs:
  publish-parcetrace-ocr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
              docker build . --tag ghcr.io/gxjakkap/aicovergen:latest
              docker push ghcr.io/gxjakkap/aicovergen:latest